### ISSUE TITLE
coordinates: false doesn't work

### ISSUE THREAD

**Issue by Allirey** [ruilisi/react-chessground#14]
It's not possible to remove coordinates with Props. 
And there is also question: how to put coordinates inside the board? (pic from lichess.org)
![image](https://user-images.githubusercontent.com/22729337/77645381-4ea76b00-6f6b-11ea-94fa-08d4b9c7eda9.png)

![image](https://user-images.githubusercontent.com/22729337/77644749-3420c200-6f6a-11ea-9d9d-b3d3d3f9e81d.png)

**Comment by hophacker** [comment]
We will fix it right now.

**Comment by fybchristasker** [comment]
We just imported signal style in this repo, but ts available to DIY your chessboard in src/index.css.
