### ISSUE TITLE
Copy default theme and assets to the chessground

### ISSUE THREAD

**Issue by MrBr** [ruilisi/react-chessground#15]
Hey,

I've recently started working with Chessground and I've missed the default theme and assets to get it working. 

It would be very useful to have your defaults there as well. 

I want to check with you if it's OK to copy your assets there?

Thanks

**Comment by fybchristasker** [comment]
Hey, you can try this demo: https://github.com/ruilisi/react-chessground-demo
import "react-chessground/dist/assets/theme.css" can works well.

**Comment by MrBr** [comment]
I am not using react-chessground, just chessground. They don't provide default assets with the board so I ought to copy yours there. It's useful for bootstrapping. Without assets, I am not getting any UI.

Do you know, should there some default preview with the base theme?
