### ISSUE TITLE
Difficulty on start up

### ISSUE THREAD

**Issue by PesceJonathan** [ruilisi/react-chessground#16]
I first want to say I love the project and the work you did here and believe that it can be useful for many projects. The one concern I have is launching the project for new coders and people new to the repo. I honestly just came across the repo today and spent a while trying to get the board to display properly. The main issue is that the class names are all wrapped in a div with a class name .merida, meaning that if you don't add the Chessground React compoenent within a div with that class name, the pieces won't render. 

![image](https://user-images.githubusercontent.com/31356845/81512056-9d2a8200-92eb-11ea-9a99-5b2f15864539.png)

I am unsure of the reason for this, maybe there is a good reason or not, but I would either change the documentation or change the CSS provided. Either way, if this is something that interests you I have no problem doing it myself and created a merge request.

Thanks again for the great project!

**Comment by fybchristasker** [comment]
Hi, we did not do some deep research,  any PR is welcome!
