### ISSUE TITLE
npm package broken!?

### ISSUE THREAD

**Issue by huberv** [ruilisi/react-chessground#21]
Hi,
when I run `npm install --save react-chessground`, the folder node_modules/react-chessground does not contain the code. Refer to the attached screenshot. I assume that the published npm package is somehow broken.

![grafik](https://user-images.githubusercontent.com/16324140/84178461-bfe3be00-aa84-11ea-915a-bbd45bd3fb4b.png)

**Comment by alexpalade** [comment]
Apparently, the package is called "[reactjs-chessground](https://www.npmjs.com/package/reactjs-chessground)". I had this problem as well, found it via the npm search. Perhaps a mistake in the readme.

**Comment by fybchristasker** [comment]
@huberv its fixed in version 1.5.0
