### ISSUE TITLE
Example using react hooks

### ISSUE THREAD

**Issue by cngeru** [ruilisi/react-chessground#28]
Can this be implemented using react-hooks and can the moves be transmitted using socket.io ?

**Comment by fybchristasker** [comment]
Temporarily, this is not supported, maybe next version.

**Comment by hophacker** [comment]
Thanks for your tips, we will do that within the next 48 hours.

**Comment by fybchristasker** [comment]
see demo in example @cngeru

**Comment by cngeru** [comment]
Thank you
@fybchristasker is it possible to transmit the moves and or fen over websockets?
