### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by victorocna** [ruilisi/react-chessground#30]
Hello everyone!

I was browsing `package.json` and found some possible tweaks:

- move `react-scripts` to devDependencies (from dependencies)
- move `react` to peerDependencies (from devDependencies)
- add `prop-types` (used in the project) to peerDependencies

What do you think? I've tested in on my machine and it did not break the build process.
I can write a PR with these changes, if you think they are all right.

**Comment by fybchristasker** [comment]
@victorocna Welcome to give PR, if your are interested.

**Comment by hophacker** [comment]
https://github.com/ruilisi/react-chessground/pull/32
