### ISSUE TITLE
Typescript support 

### ISSUE THREAD

**Issue by indolent-developer** [ruilisi/react-chessground#31]
any plans to add typescript support?

I can do a PR too if needed.

**Comment by fybchristasker** [comment]
@indolent-developer Sure, We plan to support typescript, it would be better if you are interested.

**Comment by gabrielbeauchemin** [comment]
I am also interested for my application. Please give some news about that, thanks!

**Comment by gabrielbeauchemin** [comment]
This index.d.ts seems to work to me, might need a validation or add other property that are found outside the demo:

`import React from 'react';

interface MyComponentProps {
    onMove?: (from: string, to: string) => void
    randomMove?: (moves: string[],
    move: string) => void;
    promotion?: (e: string) => void;
    reset?: () => void;
    undo?: () => void;
}

declare const Chessground: React.ComponentType<MyComponentProps>

export default Chessground`
