### ISSUE TITLE
TypeError: _a.get is not a function

### ISSUE THREAD

**Issue by ReinhardtR** [ruilisi/react-chessground#35]

**Comment by ReinhardtR** [comment]
I found the solution.

The example given in this repository is outdated. Specifically the calcMovable function.
The new way of creating that function is show here: https://github.com/ornicar/chessground-examples/blob/28ceac2c878c0187b5ad69aa68c5e25eba9f71ff/src/util.ts#L4

**Comment by JuiceDrinker** [comment]
Happy to help fix this with some pointers on where to look/start

**Comment by Roybie** [comment]
For anyone else who gets this. the answer is here https://github.com/ornicar/chessground/issues/161

dest is now a map rather than an object as in the example.
